/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    EditorButtons: typeof import('./src/components/EditorButtons.vue')['default']
    Notify: typeof import('./src/components/Notify.vue')['default']
    RecordingMessage: typeof import('./src/components/RecordingMessage.vue')['default']
  }
}
